def fun(x,y):
	try:
		return x+y
	except Exception as err:
		print(err)
